name: Deploy to prod
on:
    workflow_dispatch:
    push:
        branches:
            - master
env:
    CI: true
    TZ: Europe/Amsterdam

jobs:
    deploy-prod:
        name: Deploy application to prod
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: npm
            - name: Install dependencies
              run: npm ci --legacy-peer-deps
            - name: Run tests
              run: npm run test
            - name: Build application
              run: npm run build
              env:
                PUBLIC_URL: https://veilarbvedtaksstottefs.intern.nav.no
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v0
              with:
                  credentials_json: ${{ secrets.GCS_SA_KEY_PROD }}
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0
            - name: Upload files to GCS
              run: gsutil -m rsync -r build gs://veilarbvedtaksstottefs-prod
            - name: Create release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: release/prod@${{ github.sha }}
                release_name: Release to prod
                prerelease: false
