name: Deploy github pages
on:
    workflow_dispatch:
jobs:
    update-gh-pages:
        name: Update GitHub pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci --legacy-peer-deps
            - name: Build mock application
              run: npm run build:mock
            - name: Update GitHub pages
              uses: softprops/action-gh-release@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: github_pages
                  publish_dir: ./build
